language: java
env:
- NODE_VERSION="12.13.1"
services:
- docker
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - stage: Prepare
    script:
    - nvm install $NODE_VERSION
    - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: Build
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- echo -e "Host 129.194.10.127\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add deploy_key
- ssh -i deploy_key saberfa0@129.194.10.127 pwd
