language: java
services:
- docker
addons:
  sonarcloud:
    organization: "unigepinfo-couchpotato-frontend"
    
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - stage: Prepare
    script:
    - mvn clean install 
    - mvn verify
  - stage: Build
    script:
    - pwd
    - cd Room
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t couchpotato-backend/room-service:latest .
    - docker tag couchpotato-backend/room-service faysalsaber/room-service:latest
    - docker push faysalsaber/room-service:latest
    - cd ..
    - cd Recommendation
    - docker build -t couchpotato-backend/recommendation-service:latest .
    - docker tag couchpotato-backend/recommendation-service faysalsaber/recommendation-service:latest
    - docker push faysalsaber/recommendation-service:latest
    - cd ..
    - mvn sonar:sonar -Dsonar.projectKey=CouchpotatoBackend -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e55a69870244294e6f44dbba5b457b0db13400d8
    - ssh -i ./deploy_key saberfa0@129.194.10.127 "cd couchpotato/helm-charts/test/couchpotato-backend && source exp.sh"  
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 129.194.10.127\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key saberfa0@129.194.10.127 pwd
branches:
  only:
  - main
  - staging
  - dev

    