language: java
services:
- docker
addons:
  sonarcloud:
    organization: "unigepinfo-couchpotato-frontend" 
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - stage: Prepare
    script:
    - mvn install -N -Dmaven.javadoc.skip=true -B -V
  - stage: Build
    script:
    - pwd
    - cd Room
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t couchpotato-backend/room-service:latest .
    - docker tag couchpotato-backend/room-service faysalsaber/room-service:latest
    - docker push faysalsaber/room-service:latest
    - cd ..
    - cd Recommendation
    - docker build -t couchpotato-backend/recommendation-service:latest .
    - docker tag couchpotato-backend/recommendation-service faysalsaber/recommendation-service:latest
    - docker push faysalsaber/recommendation-service:latest
    - mvn sonar:sonar -Dsonar.projectKey=UnigePInfo-CouchPotato_couchpotato-backend  -Dsonar.organization=unigepinfo-couchpotato-frontend -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=51b83c26175058d4065bc0b8805ca492ad650e9e
    - cd ..
    - ssh -i ./deploy_key saberfa0@129.194.10.127 ls -la
    - ssh -i ./deploy_key saberfa0@129.194.10.127 cd couchpotato/helm-charts/test/couchpotato-backend/
    - ssh -i ./deploy_key saberfa0@129.194.10.127 pwd
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 129.194.10.127\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key saberfa0@129.194.10.127 pwd

