language: java
services:
- docker
addons:
  sonarcloud:
    organization: "unigepinfo-couchpotato-frontend"
    token: 
        secure: QFNTTLhkm2l0FAmWICV23KoLCM6AW28BSUgdN5R5u8W5Xv0YUaI4ZyuhvxC7rTywuDFCdXD5T9Po2g0SNViEfi3voiBjjgT9Q5YRQJGj3y7dB2pOGlyCx83K5i7UIkml/KVfX5DqQOw0jPwMkPp4ktS3c8W6GmK6ckwGOcfpp4v0pvKpi1JiFet+w522mwcNuNhlt+vaiOKJOT5pRq9jtkke0Y3vixL7Fl9hkwl948/m9y+VnY0eRkNttknfafdJt7SYW+XzSqCrPeFKK/gvlxQfRN80hp+2jShKNoD3pJqcnKjNuejBoJFFagqicBcq2xozhvldV8Y3A3fa95wILDkJe+zWHqrNVfGF1/KTf05ZpdipXcR/f8e5riWp1xC2ADlR/Cc7XvyZOfSuXILAp+XgkQOslfINQzk8mdoIURy4iodwCoxMEFL/L3jWKgGbfrnDrHn3tRPI/AgFGcICbLFwtYZ7xk6NAePXsGFkuPe6uXCFAwXmkM8tVTHd0LwYzg6kqMV4qMJJaJsyq6dftcYsP92ur9NPBVT/GqTXre0ZYNgg2GChuNv0rL4YK79HrcMk2l4tMziYU67Z1tlK0IUl/ttQ65tKE8IJJSBkbNLXF9EMxaygWJV3KV1X7+gGwcBY45tDScyTBdcbdNsXfxyCazzJ7Hlz2CCqvHfRkRk=

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - stage: Prepare
    script:
    - mvn install -N -Dmaven.javadoc.skip=true -B -V
  - stage: Build
    script:
    - pwd
    - cd Room
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t couchpotato-backend/room-service:latest .
    - docker tag couchpotato-backend/room-service faysalsaber/room-service:latest
    - docker push faysalsaber/room-service:latest
    - cd ..
    - cd Recommendation
    - docker build -t couchpotato-backend/recommendation-service:latest .
    - docker tag couchpotato-backend/recommendation-service faysalsaber/recommendation-service:latest
    - docker push faysalsaber/recommendation-service:latest
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - cd ..
    - ssh -i ./deploy_key saberfa0@129.194.10.127 cd couchpotato/helm-charts/test/couchpotato-backend/
    - ssh -i ./deploy_key saberfa0@129.194.10.127 ls -la
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 129.194.10.127\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key saberfa0@129.194.10.127 pwd
branches:
  only:
  - main
  - staging
  - dev

    