apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /users/$2
    cert-manager.io/issuer: "letsencrypt-prod"
  name: {{ include "couchpotato.fullname" . }}.ingress-api-user-management
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
    {{- include "couchpotato.labels" . | nindent 4 }}.ingress
spec:
  tls:
  - hosts:
    - api.pinfo2.unige.ch
    secretName: couchpotato-ingress-tls
  rules:
  - host: api.pinfo2.unige.ch
    http:
      paths:
      - path: /users(/|$)(.*)
        backend:
          serviceName: {{ include "couchpotato.fullname" . }}-usermanagement-service
          servicePort: 28080    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /rooms/$2
    cert-manager.io/issuer: "letsencrypt-prod"
  name: {{ include "couchpotato.fullname" . }}.ingress-api-rooms
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
    {{- include "couchpotato.labels" . | nindent 4 }}.ingress
spec:
  tls:
  - hosts:
    - api.pinfo2.unige.ch
    secretName: couchpotato-ingress-tls
  rules:
  - host: api.pinfo2.unige.ch
    http:
      paths:
      - path: /rooms(/|$)(.*)
        backend:
          serviceName: {{ include "couchpotato.fullname" . }}-room-service
          servicePort: 28080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
  name: {{ include "couchpotato.fullname" . }}.ingress-static
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
    {{- include "couchpotato.labels" . | nindent 4 }}.ingress
spec:
  tls:
  - hosts:
    - pinfo2.unige.ch
    secretName: couchpotato-ingress-tls
  rules:
  - host: pinfo2.unige.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "couchpotato.fullname" . }}-web-ui
          servicePort: 80
---    
