apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /user-management/$2
  name: {{ include "couchpotato.fullname" . }}.ingress-api-user-management
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
    {{- include "couchpotato.labels" . | nindent 4 }}.ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/users(/|$)(.*)
        backend:
          serviceName: {{ include "couchpotato.fullname" . }}-usermanagement-service
          servicePort: 28080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /rooms/$2
  name: {{ include "couchpotato.fullname" . }}.ingress-api-rooms
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
    {{- include "couchpotato.labels" . | nindent 4 }}.ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/rooms(/|$)(.*)
        backend:
          serviceName: {{ include "couchpotato.fullname" . }}-room-service
          servicePort: 28080    
  