apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "couchpotato.fullname" . }}.recommendation-service
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
    {{- include "couchpotato.labels" . | nindent 4 }}.recommendation-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "couchpotato.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "couchpotato.fullname" . }}.recommendation-service
        {{- include "couchpotato.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "couchpotato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}recommendation-service:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST
              value: "{{ .Release.Name }}-kafka"
            - name: THORNTAIL_KAFKA_DASH_CONFIGURATION_POST
              value: "9092"
            - name: THORNTAIL_PORT_OFFSET
              value: "0" 
          ports:
            - name: http
              containerPort: 28080
              protocol: TCP                         
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
