apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.oauth.OAUTH2_PROXY_CLIENT_ID | b64enc }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.oauth.OAUTH2_PROXY_CLIENT_SECRET | b64enc }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.oauth.OAUTH2_PROXY_COOKIE_SECRET | b64enc }}
