apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchpotato.fullname" . }}-recommendation-service
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}.recommendation-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "couchpotato.fullname" . }}.recommendation-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchpotato.fullname" . }}-room-service
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}.room-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "couchpotato.fullname" . }}.room-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchpotato.fullname" . }}-web-ui
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}.web-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "couchpotato.fullname" . }}.web-ui
