apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchpotato.fullname" . }}-usermanagement-service
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}.usermanagement-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "couchpotato.fullname" . }}.usermanagement-service
