apiVersion: v2
name: couchpotato
description: A Helm chart for deploying the couchpotato
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    version: 7.7.2
    repository: https://charts.helm.sh/stable
    alias: room-database
