-- -- Room table
-- TRUNCATE TABLE Room;
-- INSERT INTO Room (roomId, roomAdminId, roomClosed) VALUES ( 0, 1, FALSE );
-- INSERT INTO Room (roomId, roomAdminId, roomClosed) VALUES ( 1, 1, FALSE );
-- INSERT INTO Room (roomId, roomAdminId, roomClosed) VALUES ( 2, 6, FALSE );
-- INSERT INTO Room (roomId, roomAdminId, roomClosed) VALUES ( 3, 3, FALSE );
-- INSERT INTO Room (roomId, roomAdminId, roomClosed) VALUES ( 4, 2, TRUE );
--
-- -- Room_User table
-- ALTER TABLE Room_User DROP PRIMARY KEY;
-- ALTER TABLE Room_User ADD PRIMARY KEY (roomId, userId);
-- TRUNCATE TABLE Room_User;
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 0, 1, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 0, 2, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 0, 3, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 0, 4, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 0, 5, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 0, 6, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 0, 7, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 1, 1, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 1, 2, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 1, 3, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 2, 4, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 2, 5, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 2, 6, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 3, 3, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 4, 1, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 4, 2, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 4, 3, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 4, 4, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 4, 5, CURRENT_TIMESTAMP );
-- INSERT INTO Room_User (roomId, userId, creationDate) VALUES ( 4, 6, CURRENT_TIMESTAMP );

-- DROP SEQUENCE room_seq IF EXISTS;
-- CREATE SEQUENCE room_seq MINVALUE 0 START WITH 0 INCREMENT BY 1;